import { Injectable } from '@angular/core';
import {Actor} from '../models/Actor';


@Injectable({
  providedIn: 'root'
})
export class AppService {

  constructor() { }


  actors: Actor[] = [
    {firstName: 'Tyrion', lastName: 'Lannister', maximized: false, bio: 'Tyrion is the rarest of all things in Westeros -- a smart person with scruples. While Ned may have shown more moral fortitude, his gullibility made him a quick casualty in the game of thrones. And while Littlefinger may have more insight in how to manipulate and exploit a situation, he only ever really does it for his own benefit. But Tyrion expends those same qualities to protect a realm and a family (up to a point) that reject him at every turn. His willingness to rise above his circumstances, and his own notable failings, to turn his intelligence and connections toward doing whatever he needs to do to keep the realm safe.'},
    {firstName: 'Daenerys', lastName: 'Targaryen', maximized: false, bio: 'Whether Daenerys Targaryen proves to be a savior out of legend or a conquerer who is bad news for Westeros, there\'s no denying she is one of the most monumental characters on Game of Thrones. This series has been charting her rise to power as the character who seemingly is meant to sit on the Iron Throne since the very beginning, and her removed storyline is arguably just as important as anything happening to the West. It\'s strongly suggested she helped bring magic back into the world with the birth of her three dragons, which is no small feat to say the least. Though her ultimate role in this story remains unclear, it\'s clear Daenerys Targaryen is going to be one of the most significant players in this story through its conclusion.'},
    {firstName: 'Jon', lastName: 'Snow', maximized: false, bio: 'It’s no question why Jon Snow is one of the most important characters in Game of Thrones. Jon has all the traits of a classic hero - honor, kindness, intelligence, persistence, and selflessness. Jon proves time and time again that his duty comes before his own desires. When Jon is eventually stabbed to death in a mutiny by some of his own men, his allies desperately turn to magic in the unlikely hope they can resurrect their fallen friend, because he’s a good man and the leader they need. Outside of his life in the Night’s Watch, one of the most intriguing aspects of Jon Snow’s character is his mysterious parentage. Accepted as the illegitimate son of Ned Stark for years, Jon has never expressed interest in ruling Westeros. But if he were to have a legitimate claim to the Throne, plus the support of his Northerners as "King in the North" ... well, let\'s just say we can’t wait to see what happens when he meets Danaerys and her “children.”'},
    {firstName: 'Cersei', lastName: 'Lannister', maximized: false, bio: 'Flawed, vindictive and cunning, bullheaded, mad yet steadfast in her love of her children, there are few characters quite as dark and fascinating on Game of Thrones as Cersei Lannister. She is a woman in a man\'s world who is fighting to be a political equal of men who view her lesser simply because of her gender. Her initial warning to Ned Stark -- "when you play the game of thrones, you win or you die" -- has proved to be her mantra, though there\'s something to be respected about how she\'s still standing while more likeable and honorable people fall around her. Even when she does the most hateful, awful things and spirals into madness, we still can\'t help but respect how she\'s clawed her way to the top.'},
    {firstName: 'Arya', lastName: 'Stark', maximized: false, bio: 'Arya’s journey has had a few rough patches, both in terms of what the character has been through, and the stretches where the writers seemed to struggled to give her something interesting. But what makes her undeniably awesome is that she is the least powerful of the series’ principals, but has managed to keep her head while other stronger, smarter, and better connected Starks have lost theirs. She’s reinvented herself multiple times – a water dancer, Arry, a blind assassin, just to name a few – but her hard traveling twosome with the Hound is arguably one of the series’ best arcs.'},
    {firstName: 'Jaime', lastName: 'Lannister', maximized: false, bio: 'Forever known as the infamous Kingslayer for his treacherous assassination of the Mad King, who he was sworn to protect, Jaime Lannister was once arguably the most formidable swordsman in Westeros and a character who seemed irredeemable. His passionate love for his twin sister Cersei (yep), his soft spot for his black sheep brother Tyrion, the loss of his sword hand and subsequent humbling, the deaths of his children and father, his bonds with Brienne and Bronn -- all of these relationships and events have revealed Jaime Lannister to be a far more complicated and significant character than his earlier "Prince Charming from Shrek" persona indicated. While Jaime might not be as throughly rotten as he once seemed, he\'s still not a man to let one\'s guard down around.'},
    {firstName: 'Eddard', lastName: 'Stark', maximized: false, bio: 'Even putting aside Sean Bean’s star power, which was an important part of the show’s first season, the character of Eddard Stark does so much to set the tone of the show. His lessons about honor and loyalty and justice reverberate through the actions of his children, many of whom have become major players in the Game. And his execution in that first season further sent the message that maybe honor isn’t as practical as you might hope. Ned’s shadow looms large over the entire series, both as an example of the type of heroic figures we’re used to seeing in fantasy series, and as a major player whose actions still continue to ripple throughout the kingdom. I mean, he’s been dead for five seasons and he’s still getting new scenes.'},
    {firstName: 'Tywin', lastName: 'Lannister', maximized: false, bio: 'There are few characters in Game of Thrones that are more singularly responsible for the political climate and power standing than Tywin Lannister. The influential and rightly feared head of House Lannister was responsible for the sacking of King’s Landing during Robert’s Rebellion, effectively ending the war, setting in motion the union between his house and the crown, and planting the seeds for nearly every major plotline to follow in the capitol. On the show, Charles Dance steals nearly every scene he’s in, commanding respect with his unnerving, contemplative mood. It’s a joy to watch otherwise powerful, formidable characters pause in reverence or fear in his presence, perfectly illustrated when Tyrion exclaimed, "You just sent the most powerful man in Westeros to bed without his supper." As a force of change, he consistently drove other characters to evolve since his introduction on the show – challenging Jaime to become his true heir, forcing Cersei to put her house before herself, and reminding Tyrion of his lack of worth. Tywin is perhaps the best example, and practitioner, of the political players in Westeros.'},
    {firstName: 'Varys', lastName: '', maximized: false, bio: 'Also known as the Spider and Master of Whisperers, Varys is a spymaster is a key power player on Game of Thrones thanks to the secrets and information given to him by his informants, who he affectionately calls his “little birds.” He often finds himself at odds with Littlefinger, the only other character who can compete with him when it comes to secretly manipulating events to reach a larger goal. It was Varys who put Daenerys on the path to power and allowed Tyrion to escape execution to join her in an effort to return the Targaryens to the throne, which he claims he’s doing “for the good of the realm,” yet his true intentions are never quite certain. The calm and soft-spoken, Varys can be counted among the most dangerous and influential characters in the series.'},
    {firstName: 'Catelyn', lastName: 'Stark', maximized: false, bio: 'Catelyn Stark is so much more than just the matriarch of the Stark family. Yes, her role as the lady of Winterfell means that her influence spread far and wide across her husband and children, all of which are vital to the entire Game of Thrones saga. But past that, watching her have to stand by and watch as her entire family is torn apart figuratively and literally through a series of horrific events cements her as one of the strongest, most steadfast figures in all of Westeros. Watching her decline is absolute devastating, and The Red Wedding acting as the punctuation mark at the end of all of this exists as one of the most tragic moments in the series.'},
    {firstName: 'Sansa', lastName: 'Stark', maximized: false, bio: 'To say Sansa began Game of Thrones as the least likable member of the Stark family is an understatement. The polar opposite of her sister Arya, Sansa felt she deserved a life of luxury, as a Princess – and eventually a Queen. But as fate would have it, Sansa would instead learn some incredibly harsh and cruel lessons about how things really worked in Westeros, enduring unthinkable loses and pain along the way. What makes her stand out is that she did endure, though, not giving up where others would, and slowly but surely adapting to survive in this environment. She began to actually “play” the Game of Thrones, using Littlefinger’s unhealthy interest in her to her advantage when it counted the most, and eventually getting her well-deserved revenge on the loathsome Ramsay Bolton. She’s might never be a Cersei-level mastermind or run into battle like Arya, but Sansa’s transformation over the course of the series is one of the show’s most impressive.'},
    {firstName: 'Davos', lastName: 'Seaworth', maximized: false, bio: 'In the Game of Thrones world there aren’t many characters that are consistently likable, and genuine, without suffering a quick and terrible fate. Davos Seaworth, as of now, is one of those characters, though he’s no stranger to heartache and loss. Liam Cunningham’s gruff but lovable portrayal of Davos lends the show an element of humanity that’s often missing in the conniving machinations of the realm’s would-be kings, and supernatural high-stakes threats. It’s hard not to respect Davos, the smuggler turned kingly advisor serves as the shows de facto moral compass. He’s a humble man with a code who understands that the smart course of action is rarely the right the to do, and struggles to promote those beliefs and an internal sense of justice amid so many characters who are willing to lose themselves in the face of their own ambition. Whether he’s pushing those he believes in to believe in themselves, or delivering genuine, heartfelt pleas when all other options fail, Davos has time again proven that sacrifice in order to do what’s right for the good of the many is as kingly a goal as any claim to the throne.'},

  ];

  getActors() {
    return this.actors;
  }

}

